-- Week 1, Day 5 — Mini Project Day

CREATE DATABASE PHONE_SHOP;
SHOW DATABASES;
USE PHONE_SHOP;

CREATE TABLE PHONES(
ID INT PRIMARY KEY AUTO_INCREMENT,
BRAND VARCHAR(50),
MODEL VARCHAR(50),
PRICE INT,
STOCK INT
);
SHOW TABLES;

INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('SAMSUNG', 'GALAXY A15', 18000, 10);
INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('SAMSUNG', 'GALAXY A35', 35000, 7);
INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('SAMSUNG', 'GALAXY S23', 95000, 3);
INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('XIAOMI', 'REDMI 13C', 14000, 15);
INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('XIAOMI', 'REDMI NOTE 13', 28000, 8);
INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('XIAOMI', 'POCO X16', 42000, 6);
INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('REALME', 'C55', 16000, 12);
INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('REALME', 'NARZO 60', 24000, 6);
INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('APPLE', 'IPHONE 13', 85000, 4);
INSERT INTO PHONES (BRAND, MODEL, PRICE, STOCK) VALUES ('APPLE', 'IPHONE 14', 110000, 2);

SELECT * FROM PHONES;

SELECT * FROM PHONES
WHERE PRICE>20000;

SELECT * FROM PHONES
ORDER BY PRICE ASC;

SELECT * FROM PHONES
ORDER BY PRICE DESC
LIMIT 2;

SELECT BRAND FROM PHONES;

SELECT DISTINCT BRAND FROM PHONES;

UPDATE PHONES
SET PRICE = 20000
WHERE MODEL = 'C55';
SELECT * FROM PHONES;

DELETE FROM PHONES
WHERE MODEL = 'POCO X16';
SELECT * FROM PHONES;
